Rollback modif

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -7,16 +7,13 @@ on:
       - main
 
 jobs:
-  use-calculate-version:
-      uses: ./utils/get-version.yml
 
   release:
     if: github.event.pull_request.merged == true
     runs-on: ${{ vars.RUNNER_DISTRIBUTION }}
-    needs: use-calculate-version
     permissions:
       contents: write
-    
+
     steps:
     - name: Checkout code
       uses: actions/checkout@v2
@@ -26,25 +23,51 @@ jobs:
       with:
         dotnet-version: ${{ vars.DOTNET_VERSION }}
 
-    - name: Download artifact
-      uses: actions/download-artifact@v2
-      with:
-        name: new-version
-        path: ./artifacts
-          
-    - name: Read version and set as environment variable
-      id: set-version
+    - name: Calculate new version
+      id: calculate-version
       run: |
-        NEW_VERSION=$(cat ./artifacts/new_version.txt)
-        echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV
-        echo "New version: ${{ env.NEW_VERSION }}"
+        git fetch --tags
+        LAST_TAG=$(git tag -l "[0-9]*.[0-9]*.[0-9]*" --sort=-v:refname)
+        echo "Commande : $(git tag -l "[0-9]*.[0-9]*.[0-9]*" --sort=-v:refname)"
+        echo "Last tag: $LAST_TAG"
+
+        if [ -z "$LAST_TAG" ]; then
+          echo "No tags found that match the pattern."
+          exit 1
+        fi
+
+        # Extract the version components
+        IFS='.' read -r -a VERSION_PARTS <<< "${LAST_TAG//v/}"
+        MAJOR=${VERSION_PARTS[0]}
+        MINOR=${VERSION_PARTS[1]}
+        PATCH=${VERSION_PARTS[2]}
+
+        # Determine the new version based on PR title
+        if [[ "${{ github.event.pull_request.title }}" == *"major"* ]]; then
+          MAJOR=$((MAJOR + 1))
+          MINOR=0
+          PATCH=0
+        elif [[ "${{ github.event.pull_request.title }}" == *"minor"* ]]; then
+          MINOR=$((MINOR + 1))
+          PATCH=0
+        elif [[ "${{ github.event.pull_request.title }}" == *"patch"* ]]; then
+          PATCH=$((PATCH + 1))
+        else
+          echo "Invalid PR title for version increment. Must contain 'major', 'minor', or 'patch'."
+          exit 1
+        fi
+
+        NEW_VERSION="${MAJOR}.${MINOR}.${PATCH}"
+        echo "New version: $NEW_VERSION"
+        echo "::set-output name=new_version::$NEW_VERSION"
 
     - name: Create and push new tag
 
       env:
         GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
       run: |
-        git tag ${{ env.NEW_VERSION }}
+        NEW_VERSION=${{ steps.calculate-version.outputs.new_version }}
+        git tag $NEW_VERSION
         git push https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/AlexandreIorio/Lionk.git $NEW_VERSION
 
     - name: Create GitHub Release
@@ -53,11 +76,11 @@ jobs:
       env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       with:
-        tag_name: ${{ env.NEW_VERSION }}
-        release_name: Release ${{ env.NEW_VERSION }}
+        tag_name: ${{ steps.calculate-version.outputs.new_version }}
+        release_name: Release ${{ steps.calculate-version.outputs.new_version }}
         body: |
           # Changelog
-          ## Version ${{ env.NEW_VERSION }}
+          ## Version ${{ steps.calculate-version.outputs.new_version }}
           ${{ github.event.pull_request.body }}
         draft: false
         prerelease: false
